# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: jQuery WEUI
email: lihongxun945@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  UI lib for build hybrid wechat web app.
baseurl: "/jquery-weui" # the subpath of your site, e.g. /blog
url: "http://lihongxun945.github.io" # the base hostname & protocol for your site
twitter_username: lihongxun
github_username:  lihongxun945

# Build settings
markdown: kramdown

host: 0.0.0.0
exclude: [node_modules]
